services:
  db:
    image: postgres:15
    container_name: scooter-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=munichway
    ports:
      - "5432:5432"